apiVersion: apps/v1
kind: Deployment
metadata: 
 name: proj1-web
 labels:
   app: proj1-web
spec:
   replicas: 1 
   selector:
     matchLabels:
       app: proj1-web
   template: 
     metadata: 
       labels:
         app: proj1-web
     spec:
       containers:
         - name: proj1-web
           image: rohit4729/proj1-web:v1
           ports: 
           - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: project1
spec: 
  type: NodePort
  selector: 
    app: proj1-web
  ports: 
  -  protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 30080
